<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\Inventory\InventoryCategory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * ─────────────────────────────────────────────────────────────────────────
 *  Inventory module — Add Item (product)
 * ─────────────────────────────────────────────────────────────────────────
 *  Posts the New Product form and confirms the inventory item is created
 *  (item_code is auto-generated by the controller).
 */
class InventoryItemCreateTest extends TestCase
{
    use RefreshDatabase;

    public function test_a_product_can_be_created(): void
    {
        $this->withoutMiddleware(\App\Http\Middleware\CheckModulePermission::class);

        $user = User::factory()->create(['branch_id' => 1]);
        $name = 'DuskItem' . now()->format('His');
        $category = InventoryCategory::create([
            'name' => 'Dusk Category',
            'slug' => 'dusk-category-' . $name,
        ]);

        $resp = $this->actingAs($user)->post(route('inventory.products.store'), [
            'product_name'         => $name,
            'category_id'          => $category->id,
            // Current inventory validation (see
            // InventoryController::validateProductForm) — the form was
            // reshaped from separate purchase/consumption unit fields to a
            // single "packaging" model (e.g. "1 box = 10 pieces") after this
            // test was first written; these are the fields it now requires.
            'packaging_type'       => 'box',
            'qty_in_packaging'     => 10,
            'packaging_unit_label' => 'piece',
            'minimum_qty'          => 5,
        ]);
        $resp->assertSessionHasNoErrors();

        $this->assertDatabaseHas('inventory_items', ['product_name' => $name]);
    }
}
