<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\Inventory\InventoryCategory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * ─────────────────────────────────────────────────────────────────────────
 *  Inventory module — Add Item (product)
 * ─────────────────────────────────────────────────────────────────────────
 *  Posts the New Product form and confirms the inventory item is created
 *  (item_code is auto-generated by the controller).
 */
class InventoryItemCreateTest extends TestCase
{
    use RefreshDatabase;

    public function test_a_product_can_be_created(): void
    {
        $this->withoutMiddleware(\App\Http\Middleware\CheckModulePermission::class);

        $user = User::factory()->create(['branch_id' => 1]);
        $name = 'DuskItem' . now()->format('His');
        $category = InventoryCategory::create([
            'name' => 'Dusk Category',
            'slug' => 'dusk-category-' . $name,
        ]);

        $resp = $this->actingAs($user)->post(route('inventory.products.store'), [
            'product_name'       => $name,
            'category_id'        => $category->id,
            // Current inventory validation (see InventoryController::store):
            'inventory_behavior' => 'consumable',
            'purchase_unit'      => 'box',
            'consumption_unit'   => 'piece',
            'pieces_per_unit'    => 10,
            'minimum_qty'        => 5,
            'minimum_order_qty'  => 1,
        ]);
        $resp->assertSessionHasNoErrors();

        $this->assertDatabaseHas('inventory_items', ['product_name' => $name]);
    }
}
