<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 6 — Relationship Engine
 *
 * relationship_notifications stores in-app notifications generated by the
 * NotificationEngine. These are relationship-aware (carry relationship_id,
 * recipient_role, triggered_by_event) so they are distinct from the generic
 * app_notifications table used by the rest of the application.
 *
 * The NotificationEngine mirrors each entry to app_notifications so the
 * existing topbar bell always shows relationship notifications without any
 * changes to the bell/controller code.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('relationship_notifications', function (Blueprint $table) {
            $table->id();

            // Which relationship triggered this notification (nullable for system-wide)
            $table->foreignId('relationship_id')
                ->nullable()
                ->constrained('relationships')
                ->nullOnDelete();

            // Who should receive it — specific user OR a role broadcast
            $table->foreignId('recipient_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            // Role-based broadcast: 'doctor' | 'manager' | 'front_desk' | null
            // When set, NotificationEngine fans out to all users with that role.
            $table->string('recipient_role', 40)->nullable();

            // Event type — drives routing + deduplication
            // Examples: followup_overdue | opportunity_accepted | membership_expiring |
            //           recall_due | task_overdue | appointment_confirmed
            $table->string('type', 80)->index();

            // Display content
            $table->string('title', 255);
            $table->text('body')->nullable();

            // Deep-link to the relevant page (optional)
            $table->string('link', 500)->nullable();

            // Read / dismissed state
            $table->timestamp('read_at')->nullable();
            $table->timestamp('dismissed_at')->nullable();

            // Which ActivityEngine event caused this — observable/auditable
            $table->string('triggered_by_event', 120)->nullable();

            // Mirror ID in app_notifications (set when NotificationEngine creates the mirror)
            $table->foreignId('app_notification_id')
                ->nullable()
                ->constrained('app_notifications')
                ->nullOnDelete();

            $table->timestamps();

            // Indexes for the common queries
            $table->index(['recipient_id', 'read_at']);
            $table->index(['relationship_id', 'type', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('relationship_notifications');
    }
};
