<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * RelationshipNotification — Phase 6, Relationship Engine
 *
 * Stores notifications generated by NotificationEngine for relationship events.
 * Each record targets either a specific user (recipient_id) or all users with a
 * given role (recipient_role). The NotificationEngine fans role-based entries
 * out into per-user rows before saving.
 *
 * @property int         $id
 * @property int|null    $relationship_id
 * @property int|null    $recipient_id
 * @property string|null $recipient_role
 * @property string      $type
 * @property string      $title
 * @property string|null $body
 * @property string|null $link
 * @property \Carbon\Carbon|null $read_at
 * @property \Carbon\Carbon|null $dismissed_at
 * @property string|null $triggered_by_event
 * @property int|null    $app_notification_id
 */
class RelationshipNotification extends Model
{
    protected $table = 'relationship_notifications';

    protected $fillable = [
        'relationship_id',
        'recipient_id',
        'recipient_role',
        'type',
        'title',
        'body',
        'link',
        'read_at',
        'dismissed_at',
        'triggered_by_event',
        'app_notification_id',
    ];

    protected $casts = [
        'read_at'       => 'datetime',
        'dismissed_at'  => 'datetime',
    ];

    // ── Relationships ─────────────────────────────────────────────────────────

    public function relationship(): BelongsTo
    {
        return $this->belongsTo(Relationship::class);
    }

    public function recipient(): BelongsTo
    {
        return $this->belongsTo(User::class, 'recipient_id');
    }

    // ── Scopes ────────────────────────────────────────────────────────────────

    public function scopeForUser($query, int $userId)
    {
        return $query->where('recipient_id', $userId);
    }

    public function scopeUnread($query)
    {
        return $query->whereNull('read_at');
    }

    public function scopeNotDismissed($query)
    {
        return $query->whereNull('dismissed_at');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    public function markRead(): void
    {
        if (is_null($this->read_at)) {
            $this->update(['read_at' => now()]);
        }
    }

    public function isRead(): bool
    {
        return !is_null($this->read_at);
    }
}
