<?php

namespace App\Services\Blog;

use App\Models\Blog\BlogPost;
use App\Models\Blog\BlogPostSeo;
use App\Models\Blog\BlogPostVersion;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * All create / update / slug / versioning / restore logic for the Blog Hub,
 * kept out of the controller so BlogController stays a thin HTTP adapter.
 *
 * Three behaviours live here and are documented at their methods:
 *   - UUID          : generated by the model, referenced everywhere (routes).
 *   - Slug policy   : auto-generated + unique per clinic; editable until the
 *                     post is first published, then LOCKED (generateUniqueSlug,
 *                     resolveSlugOnUpdate, changeSlug seam).
 *   - Versioning    : snapshot() builds a self-contained restore point;
 *                     autosave() prunes to the newest 20 autosave rows while
 *                     manual/scheduled/publish snapshots are permanent.
 *
 * Loose coupling: touches only the Blog domain + the shared BlogBlockRenderer.
 * No dependency on the social mkt_posts pipeline.
 */
class BlogPostService
{
    /** Keep at most this many autosave snapshots per post. */
    public const AUTOSAVE_KEEP = 20;

    /** Words-per-minute used for the reading-time estimate. */
    private const WORDS_PER_MINUTE = 200;

    public function __construct(private BlogBlockRenderer $renderer)
    {
    }

    // =======================================================================
    // Create
    // =======================================================================

    /**
     * Create a brand-new draft. Generates the unique slug from the title and
     * derives body_html / excerpt / reading-time from body_json.
     *
     * @param array $data validated attributes (title required; body_json etc. optional)
     */
    public function createDraft(array $data, int $clinicId, ?int $userId): BlogPost
    {
        return DB::transaction(function () use ($data, $clinicId, $userId) {
            $post = new BlogPost();
            $post->clinic_id = $clinicId;
            $post->title     = $data['title'];
            $post->slug      = $this->generateUniqueSlug($clinicId, $data['slug'] ?? $data['title']);
            $post->status    = $data['status'] ?? 'draft';
            $post->author_id = $data['author_id'] ?? $userId;
            $post->category_id       = $data['category_id'] ?? null;
            $post->featured_asset_id = $data['featured_asset_id'] ?? null;
            $post->excerpt   = $data['excerpt'] ?? null;
            $post->body_json = $data['body_json'] ?? ['version' => BlogBlockSchema::VERSION, 'blocks' => []];
            $post->scheduled_at = $data['scheduled_at'] ?? null;
            $post->created_by = $userId;
            $post->updated_by = $userId;

            $this->applyContentDerivations($post);
            $post->save();

            $this->syncSeo($post, $data['seo'] ?? []);
            if (array_key_exists('tag_ids', $data)) {
                $post->tags()->sync($data['tag_ids'] ?? []);
            }

            // First real snapshot so the very first state is restorable.
            $this->writeVersion($post, BlogPostVersion::LABEL_MANUAL, $userId);

            return $post->fresh(['seo', 'tags']);
        });
    }

    // =======================================================================
    // Update / save
    // =======================================================================

    /**
     * Apply an edit to an existing post. `$versionLabel` controls whether (and
     * how) this save is snapshotted: pass a permanent label ('manual',
     * 'scheduled', 'publish') for a real save, or null to skip snapshotting
     * entirely (autosave() handles its own snapshot + prune).
     *
     * Respects the slug lock: on a post that has ever been published the slug
     * is never changed here.
     */
    public function updatePost(BlogPost $post, array $data, ?int $userId, ?string $versionLabel = BlogPostVersion::LABEL_MANUAL): BlogPost
    {
        return DB::transaction(function () use ($post, $data, $userId, $versionLabel) {
            if (array_key_exists('title', $data)) {
                $post->title = $data['title'];
            }
            if (array_key_exists('slug', $data)) {
                $post->slug = $this->resolveSlugOnUpdate($post, $data['slug']);
            }
            foreach (['excerpt', 'category_id', 'featured_asset_id', 'author_id', 'scheduled_at'] as $field) {
                if (array_key_exists($field, $data)) {
                    $post->{$field} = $data[$field];
                }
            }
            if (array_key_exists('body_json', $data)) {
                $post->body_json = $data['body_json'];
            }

            // A direct status change to 'published' is a first-publish event
            // for the slug lock (Slice 6's adapter will also call this seam).
            if (array_key_exists('status', $data) && $data['status'] !== $post->status) {
                $post->status = $data['status'];
                if ($data['status'] === 'published') {
                    $this->markFirstPublished($post);
                }
            }

            $post->updated_by = $userId;
            $this->applyContentDerivations($post);
            $post->save();

            if (array_key_exists('seo', $data)) {
                $this->syncSeo($post, $data['seo'] ?? []);
            }
            if (array_key_exists('tag_ids', $data)) {
                $post->tags()->sync($data['tag_ids'] ?? []);
            }

            if ($versionLabel !== null) {
                $this->writeVersion($post, $versionLabel, $userId);
            }

            return $post->fresh(['seo', 'tags']);
        });
    }

    /**
     * Autosave the working content, then snapshot it as an 'autosave' version
     * and prune so only the newest AUTOSAVE_KEEP autosave rows survive.
     * Permanent (manual/scheduled/publish) snapshots are never touched.
     */
    public function autosave(BlogPost $post, array $data, ?int $userId): BlogPost
    {
        return DB::transaction(function () use ($post, $data, $userId) {
            // Reuse updatePost for the working-content write, but skip its
            // snapshot — we write the autosave snapshot ourselves and prune.
            $this->updatePost($post, $data, $userId, versionLabel: null);

            $this->writeVersion($post, BlogPostVersion::LABEL_AUTOSAVE, $userId);
            $this->pruneAutosaves($post);

            return $post->fresh(['seo', 'tags']);
        });
    }

    // =======================================================================
    // Read / listing (Wave 1 Slice 5 — CMS list)
    // =======================================================================

    /**
     * Clinic-scoped, paginated post list for the CMS list page.
     *
     * Status rule: an explicit valid status filters to exactly that status.
     * With no filter (or an unrecognised one) the list defaults to "All",
     * which deliberately EXCLUDES archived posts — archived only surfaces
     * when the Archived tab is selected explicitly, so a cluttered archive
     * never buries the working set.
     */
    public function listForClinic(int $clinicId, ?string $status, ?string $search, int $perPage = 20): LengthAwarePaginator
    {
        $query = BlogPost::query()
            ->forClinic($clinicId)
            ->with(['category', 'featuredAsset', 'publications'])
            ->withCount('tags')
            ->latest('updated_at');

        if ($status !== null && in_array($status, BlogPost::STATUSES, true)) {
            $query->where('status', $status);
        } else {
            $query->where('status', '!=', 'archived');
        }

        $term = trim((string) $search);
        if ($term !== '') {
            $query->where(function ($q) use ($term) {
                $q->where('title', 'like', "%{$term}%")
                  ->orWhere('slug', 'like', "%{$term}%");
            });
        }

        return $query->paginate($perPage)->withQueryString();
    }

    /**
     * Per-status counts for the filter tabs. 'all' mirrors listForClinic()'s
     * default-view rule: every non-archived post, not a literal row count.
     */
    public function statusCounts(int $clinicId): array
    {
        $raw = BlogPost::query()
            ->forClinic($clinicId)
            ->selectRaw('status, count(*) as aggregate')
            ->groupBy('status')
            ->pluck('aggregate', 'status');

        $counts = ['all' => 0];
        foreach (BlogPost::STATUSES as $status) {
            $counts[$status] = (int) ($raw[$status] ?? 0);
            if ($status !== 'archived') {
                $counts['all'] += $counts[$status];
            }
        }

        return $counts;
    }

    // =======================================================================
    // Duplicate
    // =======================================================================

    /**
     * Clone a post into a fresh draft: new uuid (model-generated), a new
     * "-copy" slug, status draft. Copies blocks, excerpt, featured image,
     * category, SEO and tags — but NOT publications (a copy has never been
     * published anywhere) and NOT the version history.
     */
    public function duplicate(BlogPost $post, ?int $userId): BlogPost
    {
        return DB::transaction(function () use ($post, $userId) {
            $copy = new BlogPost();
            $copy->clinic_id = $post->clinic_id;
            $copy->title     = $post->title . ' (Copy)';
            $copy->slug      = $this->generateUniqueSlug($post->clinic_id, $post->slug . '-copy');
            $copy->status    = 'draft';
            $copy->excerpt   = $post->excerpt;
            $copy->body_json = $post->body_json;
            $copy->category_id       = $post->category_id;
            $copy->featured_asset_id = $post->featured_asset_id;
            $copy->author_id  = $post->author_id ?? $userId;
            $copy->created_by = $userId;
            $copy->updated_by = $userId;
            // Deliberately leave slug_locked=false / first_published_at=null:
            // a duplicate is a fresh draft whose URL is still editable.

            $this->applyContentDerivations($copy);
            $copy->save();

            if ($seo = $post->seo()->first()) {
                $this->syncSeo($copy, $seo->only([
                    'focus_keyword', 'secondary_keywords', 'meta_title', 'meta_description',
                    'canonical_url', 'og_title', 'og_description', 'og_image_asset_id', 'noindex',
                ]));
            }

            $copy->tags()->sync($post->tags()->pluck('blog_tags.id')->all());

            $this->writeVersion($copy, BlogPostVersion::LABEL_MANUAL, $userId);

            return $copy->fresh(['seo', 'tags']);
        });
    }

    // =======================================================================
    // Versioning + restore
    // =======================================================================

    /**
     * Write a self-contained snapshot: full body_json + all SEO fields +
     * title/slug/excerpt/meta at this moment, so restore() never has to
     * reassemble state from other tables.
     */
    public function writeVersion(BlogPost $post, string $label, ?int $userId): BlogPostVersion
    {
        return BlogPostVersion::create([
            'blog_post_id' => $post->id,
            'snapshot'     => $this->snapshot($post),
            'editor_id'    => $userId,
            'label'        => $label,
        ]);
    }

    /**
     * Restore a snapshot as the current working content. Restore is itself
     * undoable: a 'manual' snapshot of the PRE-restore state is written first.
     * Honours the slug lock — restoring an old slug onto a published post
     * leaves the live slug untouched.
     */
    public function restore(BlogPost $post, BlogPostVersion $version, ?int $userId): BlogPost
    {
        return DB::transaction(function () use ($post, $version, $userId) {
            // Snapshot current state first so the restore can be rolled back.
            $this->writeVersion($post, BlogPostVersion::LABEL_MANUAL, $userId);

            $snap = $version->snapshot ?? [];

            $post->title     = $snap['title'] ?? $post->title;
            $post->excerpt   = $snap['excerpt'] ?? null;
            $post->body_json = $snap['body_json'] ?? ['version' => BlogBlockSchema::VERSION, 'blocks' => []];
            $post->category_id       = $snap['category_id'] ?? null;
            $post->featured_asset_id = $snap['featured_asset_id'] ?? null;
            $post->author_id = $snap['author_id'] ?? $post->author_id;

            // Slug: only adopt the snapshot's slug if the post isn't locked.
            if (! $post->isSlugLocked() && ! empty($snap['slug']) && $snap['slug'] !== $post->slug) {
                $post->slug = $this->generateUniqueSlug($post->clinic_id, $snap['slug'], ignoreId: $post->id);
            }

            $post->updated_by = $userId;
            $this->applyContentDerivations($post);
            $post->save();

            $this->syncSeo($post, $snap['seo'] ?? []);
            if (array_key_exists('tag_ids', $snap)) {
                $post->tags()->sync($snap['tag_ids'] ?? []);
            }

            // The restore action itself is a permanent, restorable point.
            $this->writeVersion($post, BlogPostVersion::LABEL_MANUAL, $userId);

            return $post->fresh(['seo', 'tags']);
        });
    }

    /**
     * Build the self-contained snapshot array for a post.
     */
    public function snapshot(BlogPost $post): array
    {
        $seo = $post->relationLoaded('seo') ? $post->seo : $post->seo()->first();

        return [
            'title'             => $post->title,
            'slug'              => $post->slug,
            'excerpt'           => $post->excerpt,
            'body_json'         => $post->body_json,
            'reading_time'      => $post->reading_time,
            // meta
            'status'            => $post->status,
            'category_id'       => $post->category_id,
            'featured_asset_id' => $post->featured_asset_id,
            'author_id'         => $post->author_id,
            'scheduled_at'      => optional($post->scheduled_at)->toIso8601String(),
            'tag_ids'           => $post->tags()->pluck('blog_tags.id')->all(),
            'seo'               => $seo ? [
                'focus_keyword'      => $seo->focus_keyword,
                'secondary_keywords' => $seo->secondary_keywords,
                'meta_title'         => $seo->meta_title,
                'meta_description'   => $seo->meta_description,
                'canonical_url'      => $seo->canonical_url,
                'og_title'           => $seo->og_title,
                'og_description'     => $seo->og_description,
                'og_image_asset_id'  => $seo->og_image_asset_id,
                'noindex'            => $seo->noindex,
            ] : [],
        ];
    }

    /**
     * Delete autosave rows beyond AUTOSAVE_KEEP. Only label='autosave' rows are
     * ever pruned — manual/scheduled/publish snapshots are permanent.
     */
    public function pruneAutosaves(BlogPost $post): void
    {
        $keepIds = $post->versions()
            ->where('label', BlogPostVersion::LABEL_AUTOSAVE)
            ->orderByDesc('created_at')
            ->orderByDesc('id')
            ->limit(self::AUTOSAVE_KEEP)
            ->pluck('id');

        $post->versions()
            ->where('label', BlogPostVersion::LABEL_AUTOSAVE)
            ->whereNotIn('id', $keepIds)
            ->delete();
    }

    // =======================================================================
    // Slug
    // =======================================================================

    /**
     * Slugify $base and guarantee uniqueness within the clinic by appending
     * -2, -3 … on collision. Checks soft-deleted rows too (the unique index
     * (clinic_id, slug) does not exclude them).
     */
    public function generateUniqueSlug(int $clinicId, string $base, ?int $ignoreId = null): string
    {
        $slug = Str::slug($base) ?: 'post';
        $candidate = $slug;
        $suffix = 2;

        while ($this->slugExists($clinicId, $candidate, $ignoreId)) {
            $candidate = $slug . '-' . $suffix;
            $suffix++;
        }

        return $candidate;
    }

    private function slugExists(int $clinicId, string $slug, ?int $ignoreId): bool
    {
        return BlogPost::withTrashed()
            ->where('clinic_id', $clinicId)
            ->where('slug', $slug)
            ->when($ignoreId, fn ($q) => $q->where('id', '!=', $ignoreId))
            ->exists();
    }

    /**
     * Decide the slug to persist on update. Before first publish the slug is
     * freely editable (re-uniquified). After first publish it is LOCKED and the
     * incoming value is ignored — a live URL is a promise.
     */
    private function resolveSlugOnUpdate(BlogPost $post, ?string $requested): string
    {
        if ($post->isSlugLocked()) {
            return $post->slug; // locked: ignore the change
        }

        if ($requested === null || trim($requested) === '') {
            return $post->slug; // no change requested
        }

        $slugified = Str::slug($requested);
        if ($slugified === $post->slug) {
            return $post->slug;
        }

        return $this->generateUniqueSlug($post->clinic_id, $slugified, ignoreId: $post->id);
    }

    /**
     * EXTENSION POINT — NOT wired to any route yet (Slice 3+/publishing).
     *
     * The future explicit "Change URL" action for an already-published post.
     * It deliberately bypasses the lock. When a live publication exists, the
     * publishing adapter that supports redirects MUST emit an old→new redirect
     * so inbound links and SEO are preserved; that redirect flow is NOT built
     * here. Callers must gate this behind an explicit, audited user action.
     */
    public function changeSlug(BlogPost $post, string $newSlug, ?int $userId): BlogPost
    {
        $post->slug = $this->generateUniqueSlug($post->clinic_id, $newSlug, ignoreId: $post->id);
        $post->updated_by = $userId;
        $post->save();

        // TODO(Slice 6+): if $post->publications has a live target that supports
        // redirects, enqueue an old→new redirect via the WebsitePublishAdapter.

        return $post;
    }

    /**
     * Mark the first-ever publish: stamp published_at/first_published_at and
     * LOCK the slug. Exposed publicly so the Slice-6 publishing adapter can
     * call the exact same seam when a publication reaches status=published.
     */
    public function markFirstPublished(BlogPost $post): void
    {
        if ($post->first_published_at === null) {
            $post->first_published_at = now();
        }
        if ($post->published_at === null) {
            $post->published_at = now();
        }
        $post->slug_locked = true;
    }

    // =======================================================================
    // Internals
    // =======================================================================

    /**
     * Regenerate the derived fields from body_json on every save:
     *   - body_html  : rendered cache (BlogBlockRenderer)
     *   - reading_time (minutes), from the plain-text word count
     *   - excerpt    : auto-filled from the opening plain text ONLY when the
     *                  author left it blank (never overwrites a hand-written one)
     */
    private function applyContentDerivations(BlogPost $post): void
    {
        $body = is_array($post->body_json) ? $post->body_json : ['version' => BlogBlockSchema::VERSION, 'blocks' => []];

        $post->body_html = $this->renderer->render($body);

        $plain = $this->renderer->blocksToPlainText($body);
        $wordCount = $plain === '' ? 0 : count(preg_split('/\s+/', $plain, -1, PREG_SPLIT_NO_EMPTY));
        $post->reading_time = max(1, (int) ceil($wordCount / self::WORDS_PER_MINUTE));

        if (empty($post->excerpt) && $plain !== '') {
            $post->excerpt = Str::limit($plain, 157);
        }
    }

    /**
     * Upsert the 1:1 SEO row. A null/empty array leaves it untouched on update
     * but still guarantees a row exists.
     */
    private function syncSeo(BlogPost $post, array $seo): void
    {
        $row = $post->seo()->firstOrNew(['blog_post_id' => $post->id]);
        $row->fill(array_intersect_key($seo, array_flip([
            'focus_keyword', 'secondary_keywords', 'meta_title', 'meta_description',
            'canonical_url', 'og_title', 'og_description', 'og_image_asset_id', 'noindex',
        ])));
        $row->blog_post_id = $post->id;
        $row->save();
    }
}
